from __future__ import annotations

import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


SCRIPT = Path(__file__).parents[1] / "scripts" / "validate_local_onboarding.py"
SPEC = importlib.util.spec_from_file_location("validate_local_onboarding", SCRIPT)
assert SPEC and SPEC.loader
validator = importlib.util.module_from_spec(SPEC)
sys.modules[SPEC.name] = validator
SPEC.loader.exec_module(validator)


class ValidatorContractTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temp = tempfile.TemporaryDirectory()
        self.root = Path(self.temp.name)

    def tearDown(self) -> None:
        self.temp.cleanup()

    def write(self, relative: str, content: str = "") -> None:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    def test_every_nested_manifest_needs_an_owning_lock(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\n")
        self.write("backend/uv.lock")
        self.write("frontend/package.json", '{}')
        self.write("frontend/package-lock.json", '{}')
        self.assertEqual(validator.lockfile_contract(self.root)[0], "PASS")

        self.write("worker/pyproject.toml", "[project]\nname='worker'\n")
        status, detail = validator.lockfile_contract(self.root)
        self.assertEqual(status, "FAIL")
        self.assertIn("worker", detail)

    def test_workspace_lock_can_own_child_package(self) -> None:
        self.write("package.json", '{"workspaces":["apps/*"]}')
        self.write("package-lock.json", '{}')
        self.write("apps/web/package.json", '{}')
        status, _ = validator.lockfile_contract(self.root)
        self.assertEqual(status, "PASS")

    def test_frozen_sync_is_required(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\n")
        self.write("backend/uv.lock")
        self.write("frontend/package.json", '{}')
        self.write("frontend/package-lock.json", '{}')
        self.write("scripts/dev.ps1", "uv sync\nnpm install\n")
        self.assertEqual(validator.dependency_sync_contract(self.root).status, "FAIL")

        self.write("scripts/dev.ps1", "uv sync --locked\nnpm ci\n")
        self.assertEqual(validator.dependency_sync_contract(self.root).status, "PASS")

    def test_uv_project_rejects_handwritten_requirements(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        self.write("backend/requirements.txt", "fastapi==0.1.0\n")
        check = validator.package_manager_source_contract(self.root, False)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("ambiguous", check.detail)

    def test_uv_generated_requirements_is_not_a_second_source(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        self.write(
            "backend/requirements.txt",
            "# Generated by Easy2Dev from uv.lock. Do not edit.\nfastapi==0.1.0\n",
        )
        check = validator.package_manager_source_contract(self.root, False)
        self.assertEqual(check.status, "PASS")
        self.assertIn("generated uv export", check.detail)

    def test_legacy_requirements_recursively_validate_exact_pins(self) -> None:
        synthetic_vcs_reference = "git+" + "local-fixture/repo"
        self.write("backend/requirements.txt", "-r requirements-base.txt\n-c constraints.txt\n")
        self.write(
            "backend/requirements-base.txt",
            f"fastapi==0.1.0\nrepo @ {synthetic_vcs_reference}@0123456789abcdef\n",
        )
        self.write("backend/constraints.txt", "starlette==0.2.0 ; python_version >= '3.12'\n")
        check = validator.package_manager_source_contract(self.root, False)
        self.assertEqual(check.status, "PASS")
        self.assertIn("legacy pip", check.detail)

    def test_legacy_requirements_reject_unpinned_and_missing_include(self) -> None:
        self.write("backend/requirements.txt", "fastapi>=0.1\n-r missing.txt\n")
        check = validator.package_manager_source_contract(self.root, False)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("not exactly pinned", check.detail)
        self.assertIn("does not exist", check.detail)

    def test_legacy_requirements_reject_floating_git_reference(self) -> None:
        synthetic_vcs_reference = "git+" + "local-fixture/repo"
        self.write("backend/requirements.txt", f"repo @ {synthetic_vcs_reference}@main\n")
        check = validator.package_manager_source_contract(self.root, False)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("not exactly pinned", check.detail)

    def test_default_managers_reject_legacy_and_competing_js_locks(self) -> None:
        self.write("backend/requirements.txt", "fastapi==0.1.0\n")
        self.write("frontend/package.json", '{}')
        self.write("frontend/package-lock.json", '{}')
        self.write("frontend/yarn.lock")
        check = validator.package_manager_source_contract(self.root, True)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("competing lockfiles", check.detail)
        self.assertIn("legacy pip", check.detail)

    def test_runtime_install_commands_reject_ad_hoc_packages(self) -> None:
        self.write("scripts/dev.ps1", "python -m pip install fastapi\nnpm install zod\npnpm add react\n")
        check = validator.install_command_contract(self.root)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("ad hoc Python", check.detail)
        self.assertIn("npm install", check.detail)
        self.assertIn("pnpm add", check.detail)

    def test_existing_cargo_and_go_roots_require_frozen_commands(self) -> None:
        self.write("worker/Cargo.toml", "[package]\nname='worker'\nversion='0.1.0'\n")
        self.write("worker/Cargo.lock")
        self.write("service/go.mod", "module easy2dev/service\n")
        self.write("service/go.sum")
        self.write("scripts/dev.ps1", "cargo build --locked\ngo mod download\n")
        self.assertEqual(validator.dependency_sync_contract(self.root).status, "PASS")

    def test_legacy_sync_requires_checksum_and_environment_reset(self) -> None:
        self.write("backend/requirements.txt", "fastapi==0.1.0\n")
        self.write("scripts/dev.ps1", "python -m pip install -r requirements.txt\n")
        self.assertEqual(validator.dependency_sync_contract(self.root).status, "FAIL")

        self.write(
            "scripts/dev.ps1",
            "Get-FileHash requirements.txt\nRemove-Item .venv -Recurse\npython -m pip install -r requirements.txt\n",
        )
        self.assertEqual(validator.dependency_sync_contract(self.root).status, "PASS")

    def test_default_toolchain_contract_requires_versions(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\n")
        self.write("backend/uv.lock")
        self.write("frontend/package.json", '{"packageManager":"npm@11.5.0","engines":{"node":">=22"}}')
        self.write("frontend/package-lock.json", '{}')
        check = validator.toolchain_contract(self.root, True)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("Python version", check.detail)

        self.write("backend/.python-version", "3.12\n")
        self.assertEqual(validator.toolchain_contract(self.root, True).status, "PASS")

    def test_uv_tool_contract_detects_stale_lock_and_export_drift(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        self.write(
            "backend/requirements.txt",
            "# Generated by Easy2Dev from uv.lock. Do not edit.\nfastapi==0.1.0\n",
        )

        def fake_run(command: list[str], cwd: Path, timeout: int = 20) -> subprocess.CompletedProcess[str]:
            if "lock" in command:
                return subprocess.CompletedProcess(command, 1, "", "lock is stale")
            output = Path(command[command.index("--output-file") + 1])
            output.write_text("fastapi==0.2.0\n", encoding="utf-8")
            return subprocess.CompletedProcess(command, 0, "", "")

        with patch.object(validator.shutil, "which", return_value="uv"), patch.object(validator, "run", side_effect=fake_run):
            checks = validator.uv_tool_contracts(self.root, True)
        self.assertEqual(checks[0].status, "FAIL")
        self.assertEqual(checks[1].status, "FAIL")
        self.assertIn("does not match", checks[1].detail)

    def test_uv_tool_permission_failure_is_blocked(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        failed = subprocess.CompletedProcess(["uv"], 1, "", "Access is denied")
        with patch.object(validator.shutil, "which", return_value="uv"), patch.object(validator, "run", return_value=failed):
            checks = validator.uv_tool_contracts(self.root, True)
        self.assertEqual(checks[0].status, "BLOCKED")

    def test_uv_tool_contract_accepts_fresh_lock_and_matching_export(self) -> None:
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        self.write(
            "backend/requirements.txt",
            "# Generated by Easy2Dev from uv.lock. Do not edit.\nfastapi==0.1.0\n",
        )

        def fake_run(command: list[str], cwd: Path, timeout: int = 20) -> subprocess.CompletedProcess[str]:
            if "--output-file" in command:
                output = Path(command[command.index("--output-file") + 1])
                output.write_text("fastapi==0.1.0\n", encoding="utf-8")
            return subprocess.CompletedProcess(command, 0, "", "")

        with patch.object(validator.shutil, "which", return_value="uv"), patch.object(validator, "run", side_effect=fake_run):
            checks = validator.uv_tool_contracts(self.root, True)
        self.assertEqual(checks[0].status, "PASS")
        self.assertEqual(checks[1].status, "PASS")

    def test_floating_container_and_action_references_fail(self) -> None:
        self.write("backend/Dockerfile", "FROM python:latest\n")
        self.write(".github/workflows/ci.yml", "steps:\n  - uses: actions/checkout@main\n")
        check = validator.immutable_reference_contract(self.root)
        self.assertEqual(check.status, "FAIL")
        self.assertIn("floating image", check.detail)
        self.assertIn("floating action", check.detail)

    def test_standard_profile_detects_supabase_port_drift(self) -> None:
        self.write(
            "scripts/dev.ps1",
            'param([string]$Action = "up")\n# 8000 3000 54321 54323 54324\nStop-Process -Id $pid -Force\n',
        )
        self.write("supabase/config.toml", "[api]\nport = 55321\n[studio]\nport = 55323\n[inbucket]\nport = 55324\n")
        checks = validator.standard_port_contract(self.root, True)
        self.assertEqual(checks[0].status, "PASS")
        self.assertEqual(checks[1].status, "FAIL")
        self.assertIn("expected 54321", checks[1].detail)
        self.assertIn("expected 54323", checks[1].detail)

    def test_vm_contract_requires_secure_prompts(self) -> None:
        self.write("scripts/vm.ps1", "Read-Host 'frontend supabase' -AsSecureString\n")
        self.assertEqual(validator.vm_contract(self.root, True).status, "PASS")

    def test_full_default_profile_is_statically_valid(self) -> None:
        self.write("README.md", "See docs/DEV2_ONBOARDING.md\n")
        self.write("docs/DEV2_ONBOARDING.md", "Run scripts/dev.ps1\n")
        self.write(".env.example", "EXAMPLE=\n")
        self.write(".gitignore", ".env*\n!.env.example\n")
        self.write("backend/pyproject.toml", "[project]\nname='api'\nrequires-python='>=3.12'\n")
        self.write("backend/uv.lock")
        self.write(
            "frontend/package.json",
            '{"packageManager":"npm@11.5.0","engines":{"node":">=22"}}',
        )
        self.write("frontend/package-lock.json", '{}')
        self.write(
            "scripts/dev.ps1",
            '[string]$Action = "up"\n# up down status\nuv sync --locked\nnpm ci\n'
            '# 8000 3000 54321 54323 54324\nStop-Process -Id $listenerPid -Force\n',
        )
        self.write("scripts/vm.ps1", "Read-Host 'frontend supabase' -AsSecureString\n")
        self.write(
            "supabase/config.toml",
            "[api]\nport = 54321\n[studio]\nport = 54323\n[inbucket]\nport = 54324\n",
        )
        self.write("backend/Dockerfile", "FROM python:3.12-slim\nRUN uv sync --locked\n")
        checks = validator.validate(self.root, False, True, True, True)
        failures = [check for check in checks if check.status == "FAIL"]
        self.assertEqual(failures, [])


class ReleaseHygieneTests(unittest.TestCase):
    def test_packaged_skill_has_no_placeholder_or_remote_vcs_fixture(self) -> None:
        package_root = Path(__file__).parents[1]
        blocked_literals = (
            ".".join(("example", "invalid")),
            "git+" + "http://",
            "git+" + "https://",
        )
        release_paths = [package_root / "SKILL.md"]
        for directory in ("agents", "references", "scripts", "tests"):
            release_paths.extend(
                path
                for path in (package_root / directory).rglob("*")
                if path.is_file() and path.suffix in {".md", ".py", ".yaml", ".yml"}
            )

        offenders = []
        for path in release_paths:
            content = path.read_text(encoding="utf-8").lower()
            for blocked in blocked_literals:
                if blocked in content:
                    offenders.append(f"{path.relative_to(package_root)}: {blocked}")

        self.assertEqual(offenders, [])

    def test_frontend_delivery_contract_is_packaged_and_referenced(self) -> None:
        package_root = Path(__file__).parents[1]
        skill = (package_root / "SKILL.md").read_text(encoding="utf-8")
        contract_path = package_root / "references" / "frontend-delivery.md"

        self.assertTrue(contract_path.is_file())
        self.assertIn("[frontend-delivery.md](references/frontend-delivery.md)", skill)

        contract = contract_path.read_text(encoding="utf-8").lower()
        required_concepts = (
            "installed-skill catalog",
            "find-skills",
            "explicit user authorization",
            "design intent",
            "loading, empty, error, success",
            "responsive and accessibility",
            "human visual and usability acceptance",
        )
        for concept in required_concepts:
            self.assertIn(concept, contract)


if __name__ == "__main__":
    unittest.main()
