#!/usr/bin/env python3
"""Statically validate an Easy2Dev local-onboarding contract."""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path


@dataclass
class Check:
    name: str
    status: str
    detail: str


ONBOARDING_DOCS = (
    "docs/DEV2_ONBOARDING.md",
    "docs/DEVELOPER_ONBOARDING.md",
    "docs/LOCAL_DEVELOPMENT.md",
    "CONTRIBUTING.md",
)

ENV_EXAMPLES = (".env.example", "env.example")
LOCAL_ENV_NAMES = (".env", ".env.local", ".env.development.local")
SKIP_DIRS = {
    ".git",
    ".easy2dev",
    ".next",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "build",
    "coverage",
}
DEPENDENCY_CONTRACTS = {
    "package.json": ("package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lock", "bun.lockb"),
    "pyproject.toml": ("uv.lock", "poetry.lock", "pdm.lock"),
    "Cargo.toml": ("Cargo.lock",),
    "go.mod": ("go.sum",),
}
GENERATED_REQUIREMENTS_MARKERS = (
    "generated by easy2dev from uv.lock",
    "autogenerated by uv",
)
REQUIREMENT_INCLUDE_RE = re.compile(
    r"^(?:-r\s*|--requirement(?:\s+|=)|-c\s*|--constraint(?:\s+|=))(.+)$",
    re.IGNORECASE,
)
ALLOWED_REQUIREMENT_OPTIONS = (
    "--index-url",
    "--extra-index-url",
    "--trusted-host",
    "--find-links",
    "--no-index",
    "--only-binary",
    "--prefer-binary",
    "--pre",
    "--require-hashes",
)


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError):
        return ""


def is_ignored_tree(path: Path, root: Path) -> bool:
    try:
        relative = path.relative_to(root)
    except ValueError:
        return True
    return any(part in SKIP_DIRS for part in relative.parts)


def find_files(root: Path, name: str) -> list[Path]:
    return sorted(path for path in root.rglob(name) if path.is_file() and not is_ignored_tree(path, root))


def run(command: list[str], cwd: Path, timeout: int = 20) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=timeout,
        check=False,
    )


def find_onboarding_doc(root: Path) -> Path | None:
    for relative in ONBOARDING_DOCS:
        candidate = root / relative
        if candidate.is_file():
            return candidate
    return None


def lifecycle_contract(root: Path) -> tuple[bool, str]:
    candidates = (
        "scripts/dev.ps1",
        "scripts/dev.sh",
        "Makefile",
        "makefile",
        "Justfile",
        "justfile",
        "Taskfile.yml",
        "Taskfile.yaml",
    )
    incomplete = []
    for relative in candidates:
        path = root / relative
        if not path.is_file():
            continue
        lowered = read_text(path).lower()
        missing = [
            action
            for action in ("up", "down", "status")
            if re.search(rf"(?<![a-z0-9_]){action}(?![a-z0-9_])", lowered) is None
        ]
        if not missing:
            return True, relative
        incomplete.append(f"{relative} missing {', '.join(missing)}")

    package_json = root / "package.json"
    if package_json.is_file():
        try:
            scripts = json.loads(read_text(package_json)).get("scripts", {})
        except json.JSONDecodeError:
            return False, "package.json is not valid JSON"
        accepted = (
            ("dev:up", "dev:down", "dev:status"),
            ("up", "down", "status"),
        )
        for group in accepted:
            if all(name in scripts for name in group):
                return True, f"package.json scripts: {', '.join(group)}"
    if incomplete:
        return False, "; ".join(incomplete)
    return False, "no canonical up/down/status entrypoint found"


def environment_contract(root: Path) -> tuple[bool, str, bool]:
    examples = list(root.glob("*.env.example"))
    for child in root.iterdir():
        if child.is_dir() and child.name not in {".git", ".easy2dev", "node_modules", ".venv", "venv"}:
            examples.extend(child.glob("*.env.example"))
    examples.extend(root / name for name in ENV_EXAMPLES if (root / name).is_file())
    examples = sorted(set(path.resolve() for path in examples))
    compose_paths = [root / name for name in ("compose.yml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml") if (root / name).is_file()]
    compose_uses_env = any("${" in read_text(path) or "env_file:" in read_text(path) for path in compose_paths)
    env_expected = compose_uses_env or bool(examples)
    if not env_expected:
        return True, "project does not declare a local env/Compose contract", False
    if not examples:
        return False, "local environment is used but no safe env example was found", True
    return True, f"safe env example(s): {len(examples)}", True


def tracked_local_env(root: Path) -> list[str]:
    if shutil.which("git") is None or not (root / ".git").exists():
        return []
    result = run(["git", "ls-files"], root)
    if result.returncode != 0:
        return []
    tracked = []
    for raw in result.stdout.splitlines():
        name = Path(raw).name.lower()
        if name in LOCAL_ENV_NAMES:
            tracked.append(raw)
    return tracked


def local_env_candidates(root: Path) -> list[Path]:
    candidates = {root / name for name in LOCAL_ENV_NAMES}
    for example in find_files(root, ".env.example"):
        candidates.add(example.with_name(".env"))
        candidates.add(example.with_name(".env.local"))
        candidates.add(example.with_name(".env.development.local"))
    return sorted(candidates)


def ignored_local_env(root: Path) -> tuple[bool, str]:
    if shutil.which("git") is None or not (root / ".git").exists():
        gitignore = read_text(root / ".gitignore")
        ok = ".env" in gitignore
        return ok, ".gitignore contains an env rule" if ok else "cannot prove local env files are ignored"
    missing = []
    for path in local_env_candidates(root):
        relative = str(path.relative_to(root))
        result = run(["git", "check-ignore", "--no-index", "--quiet", "--", relative], root)
        if result.returncode != 0:
            missing.append(relative)
    return not missing, "all common local env files are ignored" if not missing else f"not ignored: {', '.join(missing)}"


def package_workspace_owns(manifest: Path, ancestor: Path) -> bool:
    package_json = ancestor / "package.json"
    if not package_json.is_file():
        return False
    try:
        data = json.loads(read_text(package_json))
    except json.JSONDecodeError:
        return False
    workspaces = data.get("workspaces", [])
    if isinstance(workspaces, dict):
        workspaces = workspaces.get("packages", [])
    if not isinstance(workspaces, list):
        return False
    relative_parent = manifest.parent.relative_to(ancestor).as_posix()
    return any(isinstance(pattern, str) and fnmatch.fnmatch(relative_parent, pattern.rstrip("/")) for pattern in workspaces)


def owning_lockfiles(root: Path, manifest: Path, locks: tuple[str, ...]) -> list[Path]:
    direct = [manifest.parent / lock for lock in locks if (manifest.parent / lock).is_file()]
    if direct:
        return direct
    if manifest.name != "package.json":
        return []
    ancestor = manifest.parent.parent
    while root == ancestor or root in ancestor.parents:
        candidates = [ancestor / lock for lock in locks if (ancestor / lock).is_file()]
        if candidates and package_workspace_owns(manifest, ancestor):
            return candidates
        if ancestor == root:
            break
        ancestor = ancestor.parent
    return []


def dependency_roots(root: Path) -> list[tuple[Path, tuple[Path, ...]]]:
    roots = []
    for manifest_name, locks in DEPENDENCY_CONTRACTS.items():
        for manifest in find_files(root, manifest_name):
            roots.append((manifest, tuple(owning_lockfiles(root, manifest, locks))))
    return sorted(roots, key=lambda item: item[0].as_posix())


def uv_dependency_roots(root: Path) -> list[tuple[Path, Path, Path]]:
    roots = []
    for manifest, locks in dependency_roots(root):
        uv_locks = [lock for lock in locks if lock.name == "uv.lock"]
        if manifest.name == "pyproject.toml" and uv_locks:
            roots.append((manifest.parent, manifest, uv_locks[0]))
    return roots


def primary_requirements(root: Path) -> list[Path]:
    return find_files(root, "requirements.txt")


def is_generated_uv_requirements(path: Path) -> bool:
    header = "\n".join(read_text(path).lower().splitlines()[:8])
    return any(marker in header for marker in GENERATED_REQUIREMENTS_MARKERS)


def requirement_logical_lines(path: Path) -> list[tuple[int, str]]:
    logical = []
    start_line = 0
    pending = ""
    for number, raw in enumerate(read_text(path).splitlines(), start=1):
        stripped = raw.strip()
        if not pending and (not stripped or stripped.startswith("#")):
            continue
        if not pending:
            start_line = number
        if raw.rstrip().endswith("\\"):
            pending += raw.rstrip()[:-1].strip() + " "
            continue
        line = (pending + stripped).strip()
        pending = ""
        if line:
            logical.append((start_line, line))
    if pending:
        logical.append((start_line, pending.strip()))
    return logical


def strip_inline_requirement_comment(line: str) -> str:
    return re.split(r"\s+#", line, maxsplit=1)[0].strip()


def direct_requirement_is_immutable(requirement: str) -> bool:
    core = requirement.strip()
    if core.lower().startswith("-e "):
        core = core[3:].strip()
    core = core.split(";", 1)[0].strip()
    if " @ " in core:
        url = core.split(" @ ", 1)[1].strip()
    elif core.lower().startswith("git+"):
        url = core
    else:
        return False
    if url.lower().startswith("git+"):
        return re.search(r"@[0-9a-f]{7,40}(?:#|$)", url, re.IGNORECASE) is not None
    if url.lower().startswith(("https://", "http://")):
        return re.search(r"[#&]sha256=[0-9a-f]{64}(?:&|$)", url, re.IGNORECASE) is not None
    return False


def registry_requirement_is_exact(requirement: str) -> bool:
    core = requirement.split("--hash=", 1)[0].strip()
    core = core.split(";", 1)[0].strip()
    match = re.fullmatch(
        r"[A-Za-z0-9][A-Za-z0-9_.-]*(?:\[[^\]]+\])?\s*(===|==)\s*([^\s]+)",
        core,
    )
    return bool(match and "*" not in match.group(2))


def resolve_requirement_include(current: Path, raw_value: str, root: Path) -> tuple[Path | None, str | None]:
    value = raw_value.strip().strip('"\'')
    if not value or re.match(r"^[a-z]+://", value, re.IGNORECASE):
        return None, "included requirements must be a repository file"
    candidate = (current.parent / value).resolve()
    try:
        candidate.relative_to(root)
    except ValueError:
        return None, "included requirements escape the repository"
    if not candidate.is_file():
        return None, f"included file does not exist: {value}"
    return candidate, None


def validate_legacy_requirements(primary: Path, root: Path) -> list[str]:
    errors = []
    visited: set[Path] = set()

    def visit(path: Path) -> None:
        resolved = path.resolve()
        if resolved in visited:
            return
        visited.add(resolved)
        for number, raw_line in requirement_logical_lines(resolved):
            line = strip_inline_requirement_comment(raw_line)
            if not line or line.startswith("--hash="):
                continue
            include = REQUIREMENT_INCLUDE_RE.match(line)
            if include:
                child, error = resolve_requirement_include(resolved, include.group(1), root)
                if error:
                    errors.append(f"{resolved.relative_to(root)}:{number}: {error}")
                elif child is not None:
                    visit(child)
                continue
            lowered = line.lower()
            if any(lowered == option or lowered.startswith(option + " ") or lowered.startswith(option + "=") for option in ALLOWED_REQUIREMENT_OPTIONS):
                continue
            if direct_requirement_is_immutable(line) or registry_requirement_is_exact(line):
                continue
            errors.append(f"{resolved.relative_to(root)}:{number}: dependency is not exactly pinned or immutable")

    visit(primary)
    return errors


def package_manager_source_contract(root: Path, require_default_managers: bool) -> Check:
    errors = []
    details = []
    contracts = dependency_roots(root)
    uv_dirs = {directory.resolve() for directory, _, _ in uv_dependency_roots(root)}

    for manifest, locks in contracts:
        if len(locks) > 1:
            names = ", ".join(lock.name for lock in locks)
            errors.append(f"{manifest.relative_to(root)} has competing lockfiles: {names}")
        if require_default_managers and manifest.name == "pyproject.toml" and not any(lock.name == "uv.lock" for lock in locks):
            errors.append(f"{manifest.relative_to(root)} must use uv.lock under the default-manager profile")
        if require_default_managers and manifest.name == "package.json" and not any(lock.name == "package-lock.json" for lock in locks):
            errors.append(f"{manifest.relative_to(root)} must use package-lock.json under the default-manager profile")

    legacy = []
    generated = []
    for requirements in primary_requirements(root):
        directory = requirements.parent.resolve()
        is_generated = is_generated_uv_requirements(requirements)
        has_uv = directory in uv_dirs
        relative = str(requirements.relative_to(root))
        if has_uv and not is_generated:
            errors.append(f"{relative} is hand-written beside pyproject.toml/uv.lock; Python dependency source is ambiguous")
        elif is_generated and not has_uv:
            errors.append(f"{relative} is marked as a uv export but has no owning pyproject.toml/uv.lock")
        elif is_generated:
            generated.append(relative)
        else:
            pin_errors = validate_legacy_requirements(requirements, root)
            if pin_errors:
                errors.extend(pin_errors)
            else:
                legacy.append(relative)
            if require_default_managers:
                errors.append(f"{relative} is a legacy pip source and is not allowed for a new default-manager project")

    if errors:
        return Check("dependency_source", "FAIL", "; ".join(errors))
    if contracts:
        details.append(f"{len(contracts)} manifest(s) have one owning manager")
    if generated:
        details.append(f"generated uv export(s): {', '.join(generated)}")
    if legacy:
        details.append(f"validated legacy pip source(s): {', '.join(legacy)}; migration requires approval")
    if not details:
        return Check("dependency_source", "N/A", "no recognized dependency source")
    return Check("dependency_source", "PASS", "; ".join(details))


def lockfile_contract(root: Path) -> tuple[str, str]:
    contracts = dependency_roots(root)
    if not contracts:
        return "N/A", "no recognized dependency manifest"
    missing = [str(manifest.relative_to(root)) for manifest, locks in contracts if not locks]
    if missing:
        return "FAIL", f"no owning lockfile for: {', '.join(missing)}"
    found = sorted({str(lock.relative_to(root)) for _, locks in contracts for lock in locks})
    return "PASS", f"{len(contracts)} manifest(s), lockfile(s): {', '.join(found)}"


def dependency_command_files(root: Path) -> list[Path]:
    candidates = [
        root / "scripts" / "dev.ps1",
        root / "scripts" / "dev.sh",
        root / "scripts" / "vm.ps1",
    ]
    candidates.extend(find_files(root, "Dockerfile"))
    candidates.extend(path for path in root.rglob("Dockerfile.*") if path.is_file() and not is_ignored_tree(path, root))
    workflows = root / ".github" / "workflows"
    if workflows.is_dir():
        candidates.extend(path for path in workflows.rglob("*.yml") if path.is_file())
        candidates.extend(path for path in workflows.rglob("*.yaml") if path.is_file())
    return sorted(set(path.resolve() for path in candidates if path.is_file()))


def install_command_contract(root: Path) -> Check:
    violations = []
    pattern = re.compile(r"\b(?:python(?:\.exe)?\s+-m\s+pip|pip3?|uv\s+pip)\s+install\b([^\r\n]*)", re.IGNORECASE)
    npm_pattern = re.compile(r"\bnpm\s+(?:install|i)\b([^\r\n]*)", re.IGNORECASE)
    manager_change_patterns = (
        (re.compile(r"\bpnpm\s+add\b", re.IGNORECASE), "pnpm add"),
        (re.compile(r"\byarn\s+add\b", re.IGNORECASE), "yarn add"),
        (re.compile(r"\bbun\s+add\b", re.IGNORECASE), "bun add"),
        (re.compile(r"\bpoetry\s+add\b", re.IGNORECASE), "poetry add"),
        (re.compile(r"\bpdm\s+add\b", re.IGNORECASE), "pdm add"),
        (re.compile(r"\bcargo\s+add\b", re.IGNORECASE), "cargo add"),
        (re.compile(r"\bgo\s+get\b", re.IGNORECASE), "go get"),
    )
    for path in dependency_command_files(root):
        text = "\n".join(
            line
            for line in read_text(path).splitlines()
            if not line.lstrip().startswith("#")
        )
        for match in pattern.finditer(text):
            arguments = match.group(1).lower()
            if not re.search(r"(?:^|\s)(?:-r\s*\S+|--requirement(?:\s+|=)\S+)", arguments):
                violations.append(f"{path.relative_to(root)} contains an ad hoc Python package install")
        for match in npm_pattern.finditer(text):
            violations.append(f"{path.relative_to(root)} uses npm install in runtime automation; use npm ci")
        for change_pattern, command_name in manager_change_patterns:
            if change_pattern.search(text):
                violations.append(f"{path.relative_to(root)} uses {command_name} in runtime automation; change the manifest outside startup/CI")
    if violations:
        return Check("install_commands", "FAIL", "; ".join(sorted(set(violations))))
    files = dependency_command_files(root)
    return Check("install_commands", "PASS" if files else "N/A", "no ad hoc runtime package installs" if files else "no dependency automation files")


def toolchain_contract(root: Path, require_default_managers: bool) -> Check:
    if not require_default_managers:
        return Check("toolchain_versions", "N/A", "pass --require-default-managers to enforce new-project toolchains")
    missing = []
    for directory, manifest, _ in uv_dependency_roots(root):
        text_value = read_text(manifest)
        if not (directory / ".python-version").is_file() and "requires-python" not in text_value:
            missing.append(f"{manifest.relative_to(root)} has no Python version contract")
    for manifest, locks in dependency_roots(root):
        if manifest.name != "package.json" or not any(lock.name == "package-lock.json" for lock in locks):
            continue
        if not any(lock.parent == manifest.parent for lock in locks):
            continue
        try:
            data = json.loads(read_text(manifest))
        except json.JSONDecodeError:
            missing.append(f"{manifest.relative_to(root)} is not valid JSON")
            continue
        package_manager = data.get("packageManager", "")
        node_version = data.get("engines", {}).get("node", "") if isinstance(data.get("engines", {}), dict) else ""
        if not re.fullmatch(r"npm@\d+(?:\.\d+){1,2}", package_manager):
            missing.append(f"{manifest.relative_to(root)} must pin packageManager to npm@<version>")
        if not isinstance(node_version, str) or not node_version.strip():
            missing.append(f"{manifest.relative_to(root)} must declare engines.node")
    return Check(
        "toolchain_versions",
        "FAIL" if missing else "PASS",
        "; ".join(missing) if missing else "Python and Node toolchain contracts are declared",
    )


def image_reference_is_floating(reference: str) -> bool:
    cleaned = reference.strip().strip('"\'')
    if not cleaned or cleaned == "scratch" or "$" in cleaned:
        return False
    if "@sha256:" in cleaned.lower():
        return False
    last_segment = cleaned.rsplit("/", 1)[-1]
    return ":" not in last_segment or last_segment.lower().endswith(":latest")


def immutable_reference_contract(root: Path) -> Check:
    violations = []
    dockerfiles = find_files(root, "Dockerfile")
    dockerfiles.extend(path for path in root.rglob("Dockerfile.*") if path.is_file() and not is_ignored_tree(path, root))
    for path in sorted(set(dockerfiles)):
        for number, line in enumerate(read_text(path).splitlines(), start=1):
            match = re.match(r"^\s*FROM\s+(?:--platform=\S+\s+)?(\S+)", line, re.IGNORECASE)
            if match and image_reference_is_floating(match.group(1)):
                violations.append(f"{path.relative_to(root)}:{number} uses floating image {match.group(1)}")
    for compose_name in ("compose.yml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml"):
        path = root / compose_name
        if not path.is_file():
            continue
        for number, line in enumerate(read_text(path).splitlines(), start=1):
            match = re.match(r"^\s*image:\s*([^\s#]+)", line, re.IGNORECASE)
            if match and image_reference_is_floating(match.group(1)):
                violations.append(f"{compose_name}:{number} uses floating image {match.group(1)}")
    workflows = root / ".github" / "workflows"
    if workflows.is_dir():
        for path in sorted(list(workflows.rglob("*.yml")) + list(workflows.rglob("*.yaml"))):
            for number, line in enumerate(read_text(path).splitlines(), start=1):
                match = re.match(r"^\s*-?\s*uses:\s*([^\s#]+)", line, re.IGNORECASE)
                if match and match.group(1).lower().rsplit("@", 1)[-1] in {"main", "master", "latest"}:
                    violations.append(f"{path.relative_to(root)}:{number} uses floating action {match.group(1)}")
    return Check(
        "immutable_dependencies",
        "FAIL" if violations else "PASS",
        "; ".join(violations) if violations else "container images and inspected CI actions do not use obvious floating references",
    )


def dependency_sync_contract(root: Path) -> Check:
    contracts = dependency_roots(root)
    uv_dirs = {directory.resolve() for directory, _, _ in uv_dependency_roots(root)}
    legacy_requirements = [
        path
        for path in primary_requirements(root)
        if not is_generated_uv_requirements(path) and path.parent.resolve() not in uv_dirs
    ]
    if not contracts and not legacy_requirements:
        return Check("dependency_sync", "N/A", "no recognized dependency manifest")

    searchable = dependency_command_files(root)
    text = "\n".join(read_text(path).lower() for path in searchable)
    lifecycle_text = "\n".join(
        read_text(path).lower()
        for path in (root / "scripts" / "dev.ps1", root / "scripts" / "dev.sh")
        if path.is_file()
    )
    required = set()
    for manifest, locks in contracts:
        lock_names = {lock.name for lock in locks}
        if manifest.name == "pyproject.toml":
            if "uv.lock" in lock_names:
                required.add("uv")
            elif "poetry.lock" in lock_names:
                required.add("poetry")
            elif "pdm.lock" in lock_names:
                required.add("pdm")
        if manifest.name == "package.json":
            if "package-lock.json" in lock_names:
                required.add("npm")
            elif "pnpm-lock.yaml" in lock_names:
                required.add("pnpm")
            elif "yarn.lock" in lock_names:
                required.add("yarn")
            elif {"bun.lock", "bun.lockb"} & lock_names:
                required.add("bun")
        if manifest.name == "Cargo.toml" and "Cargo.lock" in lock_names:
            required.add("cargo")
        if manifest.name == "go.mod" and "go.sum" in lock_names:
            required.add("go")
    if legacy_requirements:
        required.add("pip")

    missing = []
    if "uv" in required and not ("uv sync" in text and "--locked" in text):
        missing.append("uv sync --locked")
    if "npm" in required and "npm ci" not in text:
        missing.append("npm ci")
    if "pnpm" in required and not ("pnpm" in text and "--frozen-lockfile" in text):
        missing.append("pnpm --frozen-lockfile")
    if "yarn" in required and not ("yarn" in text and "--immutable" in text):
        missing.append("yarn --immutable")
    if "bun" in required and not ("bun install" in text and "--frozen-lockfile" in text):
        missing.append("bun install --frozen-lockfile")
    if "poetry" in required and not ("poetry install" in text and "--sync" in text):
        missing.append("poetry install --sync")
    if "pdm" in required and not ("pdm sync" in text and ("--clean" in text or "--frozen-lockfile" in text)):
        missing.append("pdm sync --clean/--frozen-lockfile")
    if "cargo" in required and not ("cargo" in text and "--locked" in text):
        missing.append("cargo command with --locked")
    if "go" in required and "go mod download" not in text:
        missing.append("go mod download")
    if "pip" in required:
        has_install = re.search(r"(?:python(?:\.exe)?\s+-m\s+pip|pip)\s+install[^\r\n]*(?:-r\s*|--requirement(?:\s+|=))requirements\.txt", lifecycle_text, re.IGNORECASE)
        has_checksum = any(token in lifecycle_text for token in ("get-filehash", "sha256sum", "shasum", "requirements.hash"))
        has_exact_reset = "pip-sync" in lifecycle_text or (
            ".venv" in lifecycle_text and any(token in lifecycle_text for token in ("remove-item", "rm -rf", "rmdir"))
        )
        if not has_install:
            missing.append("legacy pip install -r requirements.txt in the canonical lifecycle")
        if not has_checksum:
            missing.append("legacy requirements checksum detection")
        if not has_exact_reset:
            missing.append("legacy virtualenv recreation or pip-sync")
    if missing:
        return Check("dependency_sync", "FAIL", f"canonical dev/container path missing frozen sync: {', '.join(missing)}")
    return Check("dependency_sync", "PASS", "canonical dev/container path uses frozen dependency synchronization")


def strip_generated_requirements_header(text_value: str) -> str:
    lines = text_value.replace("\r\n", "\n").split("\n")
    while lines and (not lines[0].strip() or lines[0].lstrip().startswith("#")):
        lines.pop(0)
    return "\n".join(lines).strip()


def uv_failure_is_environmental(message: str) -> bool:
    lowered = message.lower()
    return any(
        token in lowered
        for token in (
            "access is denied",
            "permission denied",
            "failed to initialize cache",
            "cannot create a file",
            "python interpreter is unavailable",
        )
    )


def uv_tool_contracts(root: Path, run_tools: bool) -> list[Check]:
    uv_roots = uv_dependency_roots(root)
    exports = [path for path in primary_requirements(root) if is_generated_uv_requirements(path)]
    if not uv_roots:
        return [
            Check("uv_lock_freshness", "N/A", "no uv project"),
            Check("uv_export_drift", "N/A", "no uv project"),
        ]
    if not run_tools:
        return [
            Check("uv_lock_freshness", "NOT_RUN", "pass --run-tools to execute uv lock --check"),
            Check("uv_export_drift", "NOT_RUN" if exports else "N/A", "pass --run-tools to compare generated requirements" if exports else "no generated requirements.txt"),
        ]
    executable = shutil.which("uv")
    if executable is None:
        return [
            Check("uv_lock_freshness", "BLOCKED", "uv is unavailable"),
            Check("uv_export_drift", "BLOCKED" if exports else "N/A", "uv is unavailable" if exports else "no generated requirements.txt"),
        ]

    stale = []
    lock_blockers = []
    for directory, _, _ in uv_roots:
        result = run([executable, "lock", "--check", "--no-cache", "--project", str(directory)], directory, timeout=60)
        if result.returncode != 0:
            detail = (result.stderr or result.stdout).strip().splitlines()
            message = detail[-1] if detail else "uv lock --check failed"
            target = lock_blockers if uv_failure_is_environmental("\n".join(detail)) else stale
            target.append(f"{directory.relative_to(root)}: {message}")
    freshness = Check(
        "uv_lock_freshness",
        "FAIL" if stale else ("BLOCKED" if lock_blockers else "PASS"),
        "; ".join(stale or lock_blockers) if (stale or lock_blockers) else f"uv lock --check passed for {len(uv_roots)} project(s)",
    )

    drift = []
    export_blockers = []
    uv_dirs = {directory.resolve(): directory for directory, _, _ in uv_roots}
    for exported in exports:
        directory = uv_dirs.get(exported.parent.resolve())
        if directory is None:
            continue
        with tempfile.TemporaryDirectory() as temp_dir:
            temporary = Path(temp_dir) / "requirements.txt"
            result = run(
                [
                    executable,
                    "export",
                    "--no-cache",
                    "--locked",
                    "--format",
                    "requirements.txt",
                    "--no-dev",
                    "--no-emit-project",
                    "--no-header",
                    "--output-file",
                    str(temporary),
                    "--project",
                    str(directory),
                ],
                directory,
                timeout=120,
            )
            if result.returncode != 0 or not temporary.is_file():
                detail = (result.stderr or result.stdout).strip().splitlines()
                message = detail[-1] if detail else "uv export failed"
                target = export_blockers if uv_failure_is_environmental("\n".join(detail)) else drift
                target.append(f"{exported.relative_to(root)}: {message}")
                continue
            expected = strip_generated_requirements_header(read_text(temporary))
            actual = strip_generated_requirements_header(read_text(exported))
            if expected != actual:
                drift.append(f"{exported.relative_to(root)} does not match uv.lock")
    export_check = Check(
        "uv_export_drift",
        "FAIL" if drift else ("BLOCKED" if export_blockers else ("PASS" if exports else "N/A")),
        "; ".join(drift or export_blockers) if (drift or export_blockers) else (f"{len(exports)} generated requirements export(s) match uv.lock" if exports else "no generated requirements.txt"),
    )
    return [freshness, export_check]


def parse_toml_section_port(text: str, section: str) -> int | None:
    match = re.search(rf"(?ms)^\[{re.escape(section)}\]\s*(.*?)(?=^\[|\Z)", text)
    if not match:
        return None
    port = re.search(r"(?m)^\s*port\s*=\s*(\d+)\s*$", match.group(1))
    return int(port.group(1)) if port else None


def standard_port_contract(root: Path, required: bool) -> list[Check]:
    if not required:
        return [Check("standard_ports", "N/A", "pass --require-standard-ports to enforce the canonical profile")]
    dev_script = root / "scripts" / "dev.ps1"
    if not dev_script.is_file():
        return [Check("standard_ports", "FAIL", "scripts/dev.ps1 is required for the canonical Windows profile")]

    lowered = read_text(dev_script).lower()
    missing_tokens = [token for token in ("8000", "3000", "stop-process", "-id") if token not in lowered]
    if re.search(r"(?i)\$Action\s*=\s*['\"]up['\"]", read_text(dev_script)) is None:
        missing_tokens.append("default Action=up")
    checks = [Check(
        "standard_ports",
        "FAIL" if missing_tokens else "PASS",
        f"scripts/dev.ps1 missing: {', '.join(missing_tokens)}" if missing_tokens else "default up, backend 8000, frontend 3000, and exact-PID reclamation are declared",
    )]

    supabase_config = root / "supabase" / "config.toml"
    if supabase_config.is_file():
        config_text = read_text(supabase_config)
        api = parse_toml_section_port(config_text, "api")
        studio = parse_toml_section_port(config_text, "studio")
        mailpit = parse_toml_section_port(config_text, "inbucket")
        problems = []
        if api != 54321:
            problems.append(f"api={api!r}, expected 54321")
        if studio != 54323:
            problems.append(f"studio={studio!r}, expected 54323")
        if mailpit != 54324:
            problems.append(f"inbucket/mailpit={mailpit!r}, expected 54324")
        for port in ("54321", "54323", "54324"):
            if port not in lowered:
                problems.append(f"scripts/dev.ps1 does not report/use {port}")
        checks.append(Check(
            "supabase_ports",
            "FAIL" if problems else "PASS",
            "; ".join(problems) if problems else "Supabase API 54321, Studio 54323, and Mailpit 54324 agree with scripts/dev.ps1",
        ))
    else:
        checks.append(Check("supabase_ports", "N/A", "no supabase/config.toml"))
    return checks


def vm_contract(root: Path, required: bool) -> Check:
    path = root / "scripts" / "vm.ps1"
    if not path.is_file():
        return Check("vm_entrypoint", "FAIL" if required else "N/A", "scripts/vm.ps1 is required" if required else "VM deployment is not required")
    lowered = read_text(path).lower()
    required_tokens = ("read-host", "frontend", "supabase", "securestring")
    missing = [token for token in required_tokens if token not in lowered]
    return Check(
        "vm_entrypoint",
        "FAIL" if missing else "PASS",
        f"scripts/vm.ps1 missing contract signals: {', '.join(missing)}" if missing else "VM script prompts for frontend/Supabase configuration and secure input",
    )


def powershell_syntax_check(root: Path, relative: str, run_tools: bool) -> Check:
    ps1 = root / relative
    name = relative.replace("/", "_").replace("\\", "_").removesuffix(".ps1") + "_syntax"
    if not ps1.is_file():
        return Check(name, "N/A", f"no {relative}")
    if not run_tools:
        return Check(name, "NOT_RUN", f"pass --run-tools to parse {relative}")
    executable = shutil.which("pwsh") or shutil.which("powershell")
    if executable is None:
        return Check(name, "BLOCKED", "PowerShell parser is unavailable")
    environment = os.environ.copy()
    environment["EASY2DEV_POWERSHELL_PATH"] = str(ps1)
    parser_command = (
        "$tokens=$null; $errors=$null; "
        "[System.Management.Automation.Language.Parser]::ParseFile("
        "$env:EASY2DEV_POWERSHELL_PATH,[ref]$tokens,[ref]$errors) | Out-Null; "
        "if ($errors.Count -gt 0) { $errors | ForEach-Object { "
        "Write-Output ('line ' + $_.Extent.StartLineNumber + ': ' + $_.Message) }; exit 1 }"
    )
    result = subprocess.run(
        [executable, "-NoProfile", "-NonInteractive", "-Command", parser_command],
        cwd=root,
        capture_output=True,
        text=True,
        timeout=20,
        check=False,
        env=environment,
    )
    if result.returncode == 0:
        return Check(name, "PASS", f"{relative} parsed successfully")
    detail = (result.stderr or result.stdout).strip().splitlines()
    return Check(name, "FAIL", detail[-1] if detail else f"{relative} parse failed")


def lifecycle_syntax_check(root: Path, run_tools: bool) -> Check:
    ps1 = root / "scripts" / "dev.ps1"
    shell = root / "scripts" / "dev.sh"
    if not ps1.is_file() and not shell.is_file():
        return Check("lifecycle_syntax", "N/A", "no PowerShell or shell lifecycle script")
    if not run_tools:
        return Check("lifecycle_syntax", "NOT_RUN", "pass --run-tools to parse the lifecycle script")

    if ps1.is_file():
        parsed = powershell_syntax_check(root, "scripts/dev.ps1", run_tools)
        parsed.name = "lifecycle_syntax"
        return parsed

    executable = shutil.which("bash")
    if executable is None:
        return Check("lifecycle_syntax", "BLOCKED", "bash parser is unavailable")
    result = run([executable, "-n", str(shell)], root)
    if result.returncode == 0:
        return Check("lifecycle_syntax", "PASS", "scripts/dev.sh parsed successfully")
    detail = (result.stderr or result.stdout).strip().splitlines()
    return Check("lifecycle_syntax", "FAIL", detail[-1] if detail else "scripts/dev.sh parse failed")


def compose_check(root: Path, run_tools: bool) -> Check:
    compose_files = [name for name in ("compose.yml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml") if (root / name).is_file()]
    if not compose_files:
        return Check("compose_config", "N/A", "no Compose file")
    if not run_tools:
        return Check("compose_config", "NOT_RUN", f"found {compose_files[0]}; pass --run-tools to validate")
    docker = shutil.which("docker")
    standalone = shutil.which("docker-compose")
    if docker is not None:
        command = [docker, "compose", "config", "--quiet"]
    elif standalone is not None:
        command = [standalone, "config", "--quiet"]
    else:
        return Check("compose_config", "BLOCKED", "Docker Compose command is unavailable")
    result = run(command, root, timeout=30)
    if result.returncode == 0:
        return Check("compose_config", "PASS", compose_files[0])
    detail = (result.stderr or result.stdout).strip().splitlines()
    return Check("compose_config", "FAIL", detail[-1] if detail else "docker compose config failed")


def validate(
    root: Path,
    run_tools: bool,
    require_standard_ports: bool,
    require_vm: bool,
    require_default_managers: bool,
) -> list[Check]:
    checks: list[Check] = []

    onboarding = find_onboarding_doc(root)
    checks.append(Check("onboarding_doc", "PASS" if onboarding else "FAIL", str(onboarding.relative_to(root)) if onboarding else "no supported onboarding guide found"))

    readme = root / "README.md"
    linked = bool(onboarding and readme.is_file() and onboarding.name.lower() in read_text(readme).lower())
    checks.append(Check("readme_link", "PASS" if linked else "FAIL", "README links the onboarding guide" if linked else "README does not link the onboarding guide"))

    lifecycle_ok, lifecycle_detail = lifecycle_contract(root)
    checks.append(Check("lifecycle_entrypoint", "PASS" if lifecycle_ok else "FAIL", lifecycle_detail))

    env_ok, env_detail, env_expected = environment_contract(root)
    checks.append(Check("env_example", "PASS" if env_ok else "FAIL", env_detail))

    tracked = tracked_local_env(root)
    checks.append(Check("tracked_local_env", "FAIL" if tracked else "PASS", f"tracked: {', '.join(tracked)}" if tracked else "no common local env file is tracked"))

    if env_expected:
        ignored, ignore_detail = ignored_local_env(root)
        checks.append(Check("env_ignore", "PASS" if ignored else "FAIL", ignore_detail))
    else:
        checks.append(Check("env_ignore", "N/A", "no local env contract detected"))

    lock_status, lock_detail = lockfile_contract(root)
    checks.append(Check("lockfile", lock_status, lock_detail))
    checks.append(package_manager_source_contract(root, require_default_managers))
    checks.append(dependency_sync_contract(root))
    checks.append(install_command_contract(root))
    checks.append(toolchain_contract(root, require_default_managers))
    checks.extend(uv_tool_contracts(root, run_tools))
    checks.append(immutable_reference_contract(root))
    checks.extend(standard_port_contract(root, require_standard_ports))
    checks.append(vm_contract(root, require_vm))
    checks.append(lifecycle_syntax_check(root, run_tools))
    if (root / "scripts" / "vm.ps1").is_file():
        checks.append(powershell_syntax_check(root, "scripts/vm.ps1", run_tools))
    checks.append(compose_check(root, run_tools))
    return checks


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate a reproducible local onboarding contract.")
    parser.add_argument("--project-root", default=".", help="Repository root to inspect.")
    parser.add_argument("--run-tools", action="store_true", help="Run available external static tools such as docker compose config.")
    parser.add_argument("--require-default-managers", action="store_true", help="Require uv for new Python roots and npm for new JavaScript/TypeScript roots, plus their toolchain contracts.")
    parser.add_argument("--require-standard-ports", action="store_true", help="Require the canonical backend/frontend/Supabase port profile and exact-PID development reclamation.")
    parser.add_argument("--require-vm", action="store_true", help="Require a secure scripts/vm.ps1 deployment entrypoint.")
    parser.add_argument("--json", action="store_true", help="Emit machine-readable JSON.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = Path(args.project_root).expanduser().resolve()
    if not root.is_dir():
        print(f"Invalid project root: {root}", file=sys.stderr)
        return 2
    checks = validate(
        root,
        args.run_tools,
        args.require_standard_ports,
        args.require_vm,
        args.require_default_managers,
    )
    failing = [check for check in checks if check.status == "FAIL"]
    if args.json:
        print(json.dumps({"root": str(root), "checks": [asdict(check) for check in checks], "valid": not failing}, indent=2))
    else:
        for check in checks:
            print(f"{check.status:9} {check.name}: {check.detail}")
        print("LOCAL_ONBOARDING_VALID" if not failing else "LOCAL_ONBOARDING_INVALID")
    return 1 if failing else 0


if __name__ == "__main__":
    sys.exit(main())
